# -*- coding: utf-8 -*-
"""Spectra_Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOTnh1vsZf3Y0G1QYHLMd-g6RWm85yJQ
"""

import torch
import torch.nn as nn
import timm
import cv2
import numpy as np
from PIL import Image
from torchvision import transforms
from google.colab import files

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

class DeepfakeDetector(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = timm.create_model('efficientnet_b4', pretrained=True)
        num_features = self.backbone.classifier.in_features

        self.backbone.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(num_features, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 2)
        )

    def forward(self, x):
        return self.backbone(x)

print("Initializing model...")
model = DeepfakeDetector().to(device)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

import os
print(os.path.exists('/content/genvscan_final-3.pth'))

model.load_state_dict(torch.load('/content/genvscan_weights_only.pth', map_location=device, weights_only=True))
model.eval()

CONFIG = {
    'batch_size': 32,
    'num_epochs': 20,
    'learning_rate': 1e-4,
    'image_size': 224,
    'num_workers': 2
}

val_transform = transforms.Compose([
    transforms.Resize((CONFIG['image_size'], CONFIG['image_size'])),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def get_tta_transforms():
    base_norm = {'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225]}
    return [
        transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize(**base_norm)]),
        transforms.Compose([transforms.Resize((224, 224)), transforms.RandomHorizontalFlip(p=1.0), transforms.ToTensor(), transforms.Normalize(**base_norm)]),
        transforms.Compose([transforms.Resize((256, 256)), transforms.CenterCrop(224), transforms.ToTensor(), transforms.Normalize(**base_norm)]),
        transforms.Compose([transforms.Resize((256, 256)), transforms.CenterCrop(224), transforms.RandomHorizontalFlip(p=1.0), transforms.ToTensor(), transforms.Normalize(**base_norm)]),
        transforms.Compose([transforms.Resize((288, 288)), transforms.CenterCrop(224), transforms.ToTensor(), transforms.Normalize(**base_norm)]),
    ]

tta = get_tta_transforms()

print("Upload a video to analyze:")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]

cap = cv2.VideoCapture(video_path)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps = cap.get(cv2.CAP_PROP_FPS)
duration = total_frames / fps
num_frames = min(max(int(duration * 2), 16), 64)
frame_indices = np.linspace(0, total_frames - 1, num_frames, dtype=int)

all_probs = []
all_confs = []

for idx in frame_indices:
    cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
    ret, frame = cap.read()
    if not ret:
        continue
    frame_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    frame_probs = []
    for t in tta:
        tensor = t(frame_pil).unsqueeze(0).to(device)
        with torch.no_grad():
            p = torch.softmax(model(tensor), dim=1)[0].cpu().numpy()
        frame_probs.append(p)
    probs = np.mean(frame_probs, axis=0)
    all_probs.append(probs)
    all_confs.append(max(probs))

cap.release()

all_probs = np.array(all_probs)
all_confs = np.array(all_confs)
weights = all_confs / all_confs.sum()
weighted_probs = np.average(all_probs, axis=0, weights=weights)
final_label = "AI-Generated" if np.argmax(weighted_probs) == 1 else "Real"

result = {
    'label': final_label,
    'confidence': max(weighted_probs) * 100,
    'real': weighted_probs[0] * 100,
    'fake': weighted_probs[1] * 100,
    'frames': len(all_probs),
    'duration': duration
}
result

print(f'''
Detection: {result['label']}
Confidence: {result['confidence']:.2f}%
Real: {result['real']:.2f}%
AI-Generated: {result['fake']:.2f}%
Frames: {result['frames']}
Duration: {result['duration']:.1f}s
''')

from transformers import BlipProcessor, BlipForConditionalGeneration

caption_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
caption_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large",
    torch_dtype=torch.float16,
).to(device)
caption_model.eval()

def describe_video(video_path, num_caption_frames=5):
    cap = cv2.VideoCapture(video_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    indices = np.linspace(0, total - 1, num_caption_frames, dtype=int)

    captions = []
    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ok, frame = cap.read()
        if not ok:
            continue
        img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        inputs = caption_processor(images=img, return_tensors="pt").to(device, torch.float16)
        with torch.no_grad():
            out = caption_model.generate(**inputs, max_new_tokens=40)
        captions.append(caption_processor.decode(out[0], skip_special_tokens=True).strip())
    cap.release()

    # Deduplicate similar captions
    unique = []
    for c in captions:
        if not any(c.lower() == u.lower() for u in unique):
            unique.append(c)

    if len(unique) == 1:
        return unique[0]
    return "The video shows: " + "; then ".join(unique) + "."

# Generate description for the video uploaded in the previous cell
video_description = describe_video(video_path)
print("Video description:", video_description)

from groq import Groq

client = Groq(api_key="-")


system_prompt = f"""You are Spectra, an AI-powered video authenticity detection assistant.

Your purpose: Help users understand whether a video is real or AI-generated,
and answer their questions about what is happening in the video.

Capabilities:
- You analyze videos using a deep learning detection model (EfficientNet-B4)
- You have access to a textual description of the video's visual content,
  produced by a separate video captioning model (BLIP)
- You explain detection results in simple terms
- You point out visual cues that typically indicate real or AI-generated content,
  such as temporal inconsistencies, unnatural motion, warped facial features,
  inconsistent lighting, texture issues, and anatomical errors (hands, teeth, eyes) dont mention your capabilities if you wehre not asked to

Personality:
- Concise and direct
- Friendly but professional
- Always respond in the same language the user uses (English or Arabic)
- Always refer to yourself as Spectra

How to use the information:
- If the user asks what is in the video, use the video description.
- If the user asks why the video was flagged, reason from the confidence scores
  AND the visual content described below.
- Acknowledge model limitations honestly, especially when confidence is low.

Current Detection Results:
- Prediction: {result['label']}
- Confidence: {result['confidence']:.2f}%

Video Content Description:
{video_description}

Only share the prediction and confidence with the user when relevant. You may
reference the video content naturally when answering questions about it.
"""

messages = [{"role": "system", "content": system_prompt}]

while True:
    user_input = input("You: ")
    if user_input.lower() in ['quit', 'exit']:
        break

    messages.append({"role": "user", "content": user_input})

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages
    )

    reply = response.choices[0].message.content
    messages.append({"role": "assistant", "content": reply})
    print(f"\nSpectra: {reply}\n")